# Generated by Django 5.0.2 on 2024-02-20 17:07

import django.core.validators
import user_profile.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(2)])),
                ('first_name', models.CharField(max_length=20, validators=[user_profile.models.validate_name_capital])),
                ('last_name', models.CharField(max_length=20, validators=[user_profile.models.validate_name_capital])),
                ('picture', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
