# Generated by Django 5.0.2 on 2024-02-18 21:37

import django.core.validators
import user_profile.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25, validators=[django.core.validators.MinLengthValidator(2), user_profile.models.validate_username])),
                ('last_name', models.CharField(max_length=35, validators=[django.core.validators.MinLengthValidator(2), user_profile.models.validate_username])),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('password', models.CharField(help_text='*Password length requirements: 8 to 20 characters', max_length=20, validators=[django.core.validators.MinLengthValidator(8)])),
                ('image_url', models.URLField()),
                ('age', models.PositiveIntegerField(default=18)),
            ],
        ),
    ]
